apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodepool
                    operator: In
                    values:
                      - yangao
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: demoapp
        matchLabelKeys:
        - pod-template-hash
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      terminationGracePeriodSeconds: 600
      serviceAccount: default
      serviceAccountName: default
      initContainers:
      - name: init-sysctl
        image: 'registry-vpc.cn-beijing.aliyuncs.com/acs/busybox:v1.29.2'
        command:
          - /bin/sh
          - '-c'
          - |
            mount -o remount rw /proc/sys
            sysctl -w net.netfilter.nf_conntrack_max=1503232
            sysctl -w net.netfilter.nf_conntrack_buckets=375808
            sysctl -w net.netfilter.nf_conntrack_tcp_timeout_time_wait=60
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
          sysctls:
          - name: net.core.somaxconn
          value: "1024"
          - name: kernel.msgmax
          value: "65536"
          allowPrivilegeEscalation: true
      containers:
      - name: demoapp
        image: registry.cn-hangzhou.aliyuncs.com/opensf/demoapp:v1.0
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - '-c'
                - >-
                  echo "hello" >> /etc/hosts
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 600
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: disk
          mountPath: /data
      volumes:
      # - name: disk
      #   persistentVolumeClaim:
      #     claimName: nas-test-delete
      - name: disk
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-deploy
spec:
  selector:
    app: demoapp
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      nodeName: cn-shanghai.10.132.135.209
      containers:
      - name: demoapp
        image: registry.cn-hangzhou.aliyuncs.com/opensf/demoapp:v1.0
        ports:
        - containerPort: 80
          name: http
