apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
spec:
  containers:
  - name: demoapp
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
