# 通过openkruise，进行多域管理
# https://help.aliyun.com/zh/ack/ack-managed-and-ack-dedicated/user-guide/use-openkruise-to-deploy-cloud-native-applications?spm=a2c4g.11186623.0.i5
apiVersion: apps.kruise.io/v1alpha1
kind: UnitedDeployment
metadata:
  name: sample-ud
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sample
  template:
    # 负载模版定义
    deploymentTemplate:
      metadata:
        labels:
          app: sample
      spec:
        selector:
          matchLabels:
            app: sample
        template:
          metadata:
            labels:
              app: sample
          spec:
            containers:
            - image: registry.cn-hangzhou.aliyuncs.com/opensf/demoapp:v1.0
              name: nginx
  # 多域管理
  topology:
    subsets:
    - name: ecs
      nodeSelectorTerm:
        matchExpressions:
        - key: type
          operator: NotIn
          values:
          - virtual-kubelet
      replicas: 3
    - name: eci
      nodeSelectorTerm:
        matchExpressions:
        - key: type
          operator: In
          values:
          - virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        effect: NoSchedule
        operator: In
        value: alibabacloud