apiVersion: v1
kind: Pod
metadata:
  name: volumes-rbd-demo
spec:
  containers:
  - name: redis
    image: redis:alpine
    ports:
    - containerPort: 6379
      name: redisport
    volumeMounts:
    - mountPath: /data
      name: redis-rbd-vol
  volumes:
    - name: redis-rbd-vol
      rbd:
        monitors:
        - '172.29.200.1:6789'
        - '172.29.200.2:6789'
        - '172.29.200.3:6789'
        pool: kube
        image: redis-img1
        fsType: xfs
        readOnly: false
        user: kube
        keyring: /etc/ceph/ceph.client.kube.keyring
