kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mason-admin
  namespace: dev
subjects:
- kind: User
  name: mason
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
