apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- namespace.yaml
- ../base/

namespace: dev
namePrefix: dev-

labels:
- includeSelectors: true
  pairs:
    env: dev

configMapGenerator:
- literals:
  - host="0.0.0.0"
  - port="80"
  name: demoapp-conf

patches:
- path: patches/demoapp-deployment-add-config.yaml

generatorOptions:
  disableNameSuffixHash: true
