apiVersion: v1
data:
  Corefile: |
    .:53 {
        hosts {
          172.29.9.1 k8s-master01.ilinux.io
          172.29.9.11 k8s-node01.ilinux.io
          172.29.9.12 k8s-node02.ilinux.io
          172.29.9.13 k8s-node03.ilinux.io
          fallthrough
        }
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
