apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
spec:
  template:
    spec:
      containers:
      - name: demoapp
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: demoapp-conf
              key: demoapp.port
              optional: false
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: demoapp-conf
              key: demoapp.host
              optional: true
        volumeMounts:
        - name: demoappcerts
          mountPath: /etc/demoapp/certs/
          readOnly: true
      volumes:
      - name: demoappcerts
        secret:
          secretName: demoapp-ssl
