---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:5.5.3-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: wordpress.db.name
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: user.username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: user.password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-stor
          mountPath: /var/www/html
      volumes:
      - name: wordpress-stor
        persistentVolumeClaim:
          claimName: wordpress-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
