apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
bindTimeoutSeconds: 600
algorithmSource:
  policy:
    file:
      path: /etc/kubernetes/scheduler/policy.cfg
  provider: DefaultProvider
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
disablePreemption: false
