apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-endpoints
subsets:
  - addresses:
    - ip: gfs01.ilinux.io
    ports:
    - port: 24007 
      name: glusterd
  - addresses:
    - ip: gfs02.ilinux.io
    ports:
    - port: 24007 
      name: glusterd
  - addresses:
    - ip: gfs03.ilinux.io
    ports:
    - port: 24007 
      name: glusterd
