apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base/

resources:
- namespace.yaml

namespace: prod

commonLabels:
  environment: prod

commonAnnotations:
  ilinux.io/app: "demoapp" 

configMapGenerator:
- name: demoapp-conf
  literals:
  - host="0.0.0.0"
  - port="8080"

secretGenerator:
- name: demoapp-ssl
  files:
  - secrets/tls.crt
  - secrets/tls.key
  type: "kubernetes.io/tls"

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- patches/demoapp-add-requests-and-limits.yaml
- patches/demoapp-add-configmap-and-secret.yaml

patchesJson6902:
- target:
    version: v1
    kind: Service
    name: demoapp
  path: patches/patch-service-demoapp-targetport-8080.yaml
